### ISSUE TITLE
[FE] position값을 관리하는 PositionManager Class 구현

### ISSUE THREAD

**Issue by dahun-lee-daji** [dahun-lee-daji/todo-list#14]
# 요구 사항
- [x] new card 기능 시 [CellData]중 가장 큰Pos값을 참조하여 newCard.pos = [CellData].first(가장 큰 Pos값을 가진 객체).Pos + gap 하는 method
- [ ] card의 index 이동 시 (위쪽card.pos + 아래쪽card.pos) / 2 
- [x] 첫 번째 카드는 10^3자리의 수
- [x] 이후의 카드는 += gap 만큼 더하여 pos값을 부여.
- [ ] 다른 CellData에서 pos 값이 같아질 경우, CellData가 overflow될 경우, 전체 CellData에 대한 pos값을 교정 후 server post

# 참고 자료
@Polynomeer 가 보여줬던 StackOverFlow Link

**Comment by polynomeer** [comment]
### Trello 에서 카드 이동을 position으로 구현하는 방법
- https://news.ycombinator.com/item?id=10957165
- https://community.developer.atlassian.com/t/how-to-know-the-position-of-a-card-checklist-list/35844
- https://stackoverflow.com/questions/14446859/what-does-the-pos-actually-mean-in-the-trello-api

### Trello clone project example
- https://github.com/jeonghwan-kim/lecture-vue-trello/blob/card/move/src/components/Board.vue
위의 예제를 보면 코드 상에서 `position+=gap` 이 아니라 `next_card.position*2` 나 `prev_card.position/2` 와 같이 구현하였는데, 이 부분도 참고하시면 좋을 것 같습니다!
