### ISSUE TITLE
[FE, BE] 전달될 데이터 형식 협의

### ISSUE THREAD

**Issue by dahun-lee-daji** [dahun-lee-daji/todo-list#4]
```swift
class testCellData : Codable {
    var cardId : Int
    var title : String
    var content: String
    var isApp : Bool
    var createdTime : String
    var position: Int
    var columnId : Int
}
```
Cell의 타이틀 : title
Cell의 Body : content
앱에서 작성됐는지 여부 : isApp
yyyyMMdd HH:mm:ss로 표현될 createdTime -> 날짜 기준으로 정렬 예정
pos : 카드의 최신 순을 결정하는 인덱스

``` swift
class testHistory : Codable {
    var author : String = ""
    var title : String = ""
    var action : String//historyAction
    var from : String?
    var to : String?
    var date : String

//    enum historyAction : String {
//        case add = "add"
//        case remove = "remove"
//        case update = "update"
//        case move = "move"
//    }
}
```
@author 가 title을 action, from \(from) to \(to)
history 작성 주체 : author
history 생성 시간 : date
action이 적용된 CellDate 객체 구분 : title
action : 주석 처리된 액션
from : title이 원래 있던 section
to : title이 이동 할 section

**Comment by dahun-lee-daji** [comment]
쉬시는데 요청드려 죄송합니다. @Polynomeer , @jihye-woo 
요청사항 :
1. History의 반환형 변경 : 현재 Array -> 요청 Dictionary
2. History Data를 6~8개까지 증량 요청
3. History Data의 Date를 각각 다르게 변경 요청
4. CellData 또한 Dictionary로 변경 부탁드립니다.

**Comment by jihye-woo** [comment]
아닙니다! @dahun-lee-daji @jhpark-ZG 정말 열심히 하시네용👍
저희도.. 내일부터 다시 런런하도록 하겠습니다..!🏃‍♀️🏃

1. 요청 Dictionary라는 말을 정확하게 이해하지 못했습니다😂 혹시 조금 더 설명해주실 수 있을까요?
2. 넵!
3. 넵 알겠습니다!!
4. 1번을 해결하면 4번도 이해할 수 있을 것 같네요!✨👀

**Comment by dahun-lee-daji** [comment]
현재 /api/histories 요청을 보내면 반환형이 Array로 전달되고 있습니다. 
이를 Dictionary로 받으려하는데, BackEnd에서 컨트롤 가능한 부분인가요?😄
만약,, 아니라면 새로운 방법을 찾아보겠습니다!

**Comment by jihye-woo** [comment]
앗.. 제가 Dictionary에 대해서 정확하게 이해를 잘 못하고 있는 것 같네요...!ㅠㅠ
- Array 형식 : 저희가 전달해 드린대로 [{ 히스토리 데이터 1 }, { 히스토리 데이터2 }, {}, ...]
- Dictionary 형식 : ?? 

구글링을 해봤는데도 어떤 형태인지 감이 오지 않아서 다시 질문드립니다.
혹시 예시를 들어주실 수 있을까요? 한 번에 이해하지 못해서 죄송해용😂😂

**Comment by dahun-lee-daji** [comment]
어제 밤에 요청드렸던 1,4번 항목은 신경쓰시지 않으셔도 될 것 같습니다.
제가 뇌가 굳어서 실수 한 것 같습니다. 혼란스럽게 해드려 죄송합니다 ㅜㅜ
시간을 보상해드리고 싶네요 😭😭😭😭

**Comment by jihye-woo** [comment]
엣 아니에요! 제가 Dictionary에 대한 이해가 많이 없었어서ㅠㅠ 죄송해요 
다우니는 java에서는 HashMap이라는 걸로 사용되는 것까지 찾아와주셨는데🥲🥲 완전 감동..✨🥺
덕분에 ios에서는 HashMap을 Dictionary라는 이름으로 사용하는구나 하나 알아갔습니다!!💡 감사해요👍

**Comment by jihye-woo** [comment]
말씀해주신대로 `/api/histories` 요청이 들어왔을 때 
**7개**의 **다른 date**를 가진 histories 데이터를 반환하도록 했습니다

반환되는 데이터는 아래와 같습니다! (어휴.. 눈이 아프네요👀)
```
[{"author":"August","title":"title1","action":"add","from":null,"to":"ToDo","date":"2021-04-14 13:41:27"},
{"author":"roach","title":"title2","action":"move","from":"ToDo","to":"Doing","date":"2021-04-14 13:43:27"},
{"author":"Woody","title":"title3","action":"update","from":"ToDo","to":null,"date":"2021-04-14 17:38:27"},
{"author":"Downey","title":"title4","action":"remove","from":"Done","to":null,"date":"2021-04-19 13:39:07"},
{"author":"Downey","title":"title5","action":"add","from":"ToDo","to":null,"date":"2021-04-15 18:38:27"},
{"author":"ZG","title":"title6","action":"move","from":"Doing","to":"Done","date":"2021-04-21 13:38:27"},
{"author":"ZG","title":"title7","action":"move","from":"ToDo","to":"Doing","date":"2021-04-24 13:38:27"}]
```
👉 바로가기 : http://54.180.218.17:8080/api/histories

**Comment by dahun-lee-daji** [comment]
감사합니다!
